language: python

python:
  - 3.4

env:
  - DEPS="scipy pyyaml pillow pandas h5py sphinx matplotlib nose emcee"


install:
  - sudo apt-get install gfortran
  - conda create -n testenv --yes pip python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install -c conda-forge --yes $DEPS
  - pip install numpy==1.14.1
  - pip install xarray==0.10.0
  - python setup.py install
  - python setup.py build_ext --inplace

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda2-4.2.11-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-4.2.11-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then export PATH=/home/travis/miniconda2/bin:$PATH; else export PATH=/home/travis/miniconda3/bin:$PATH; fi
  # Learned the hard way: miniconda is not always up-to-date with conda.
  - conda update --yes conda

script: python run_nose.py
